package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

@Config
public class RobotConfig {
    public static double
            HEIGHT_FLOOR = 0,
            HEIGHT_TWO = 1.25,
            HEIGHT_THREE = 2.5,
            HEIGHT_FOUR = 3.75,
            HEIGHT_FIVE = 5,
            HEIGHT_LOW = 15.8365,
            HEIGHT_MEDIUM = 25.365,
            HEIGHT_TALL = 36.50375,
            HEIGHT_STAGES_FOUR = 28.8,
            HEIGHT_STAGES_THREE = 19.2,
            HEIGHT_STAGES_TWO = 9.6,
            LIFT_kG_FOUR = 0.0,
            LIFT_kG_THREE = 0.0,
            LIFT_kG_TWO = 0.0,
            LIFT_kG_ONE = 0.0,
            LIFT_kP = 0.0,
            LIFT_kI = 0.0,
            LIFT_kD = 0.0,
            LIFT_kV = 0.0,
            LIFT_kA = 0.0,
            LIFT_kS = 0.0,
            LIFT_PID_FILTER_GAIN = 0.98,
            LIFT_VELO_FILTER_GAIN = 0.796,
            LIFT_ACCEL_FILTER_GAIN = 0.95,
            LIFT_JERK_FILTER_GAIN = 0.95,
            LIFT_MAX_UP_VELO = 10,
            LIFT_MAX_UP_ACCEL = 10,
            LIFT_MAX_DOWN_VELO = 10,
            LIFT_MAX_DOWN_ACCEL = 10,
            LIFT_MAX_JERK = 10,
            LIFT_INTEGRATION_MAX_VELO = 0.8,
            LIFT_POS_TOLERANCE = 0.15843625,
            LIFT_INCHES_PER_TICK = 0.03168725,
            PRECISION_MODE_SCALE = 0.3,
            ANGLE_CLAW_CLOSED = 5,
            ANGLE_CLAW_PASS = 30,
            ANGLE_CLAW_OPEN = 67,
            ANGLE_ARM_UP = 0,
            ANGLE_ARM_DOWN = 110,
            ANGLE_PIVOT_FRONT = 12,
            ANGLE_PIVOT_BACK = 210,
            ANGLE_PASS_FRONT = 5,
            ANGLE_PASS_TILT = 45,
            ANGLE_PASS_PIVOT = 90,
            ANGLE_PASS_BACK = 310,
            TIME_CLAW = 0.1,
            TIME_FRONT_PIVOT = 0.3,
            TIME_PIVOTING = 0.1,
            TIME_BACK_PIVOT = 0.4,
            TIME_LIFT_MEDIUM = 0.8,
            TIME_LIFT_TALL = 1,
            CAMERA_FX = 578.272,
            CAMERA_FY = 578.272,
            CAMERA_CX = 402.145,
            CAMERA_CY = 221.506;

    public static int
            LIFT_PID_ESTIMATE_COUNT = 5,
            LIFT_VELO_ESTIMATE_COUNT = 5,
            LIFT_ACCEL_ESTIMATE_COUNT = 5,
            LIFT_JERK_ESTIMATE_COUNT = 5;
}
