package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

@Config
public class RobotConfig {
    public static double
            HEIGHT_FLOOR = 0,
            HEIGHT_TWO = 1.35,
            HEIGHT_THREE = 2.7,
            HEIGHT_FOUR = 4.05,
            HEIGHT_FIVE = 5.4,
            HEIGHT_LOW = 6.2,
            HEIGHT_MEDIUM = 16.4,
            HEIGHT_TALL = 26.6,
            HEIGHT_STAGES_FOUR = 28.8,
            HEIGHT_STAGES_THREE = 19.2,
            HEIGHT_STAGES_TWO = 9.6,
            LIFT_kG_FOUR = 0.1,
            LIFT_kG_THREE = 0.08,
            LIFT_kG_TWO = 0.06,
            LIFT_kG_ONE = 0.04,
            LIFT_kP = 0.15,
            LIFT_kI = 0.21,
            LIFT_kD = 0.0,
            LIFT_UP_kV = 0.019,
            LIFT_UP_kA = 0.001,
            LIFT_UP_kS = 0.0,
            LIFT_DOWN_kV = 0.0087,
            LIFT_DOWN_kA = 0.0005,
            LIFT_DOWN_kS = 0.0,
            LIFT_PID_FILTER_GAIN = 0.98,
            LIFT_VELO_FILTER_GAIN = 0.8,
            LIFT_ACCEL_FILTER_GAIN = 0.8,
            LIFT_JERK_FILTER_GAIN = 0.8,
            LIFT_MAX_VELO = 39,
            LIFT_MAX_ACCEL = 200,
            LIFT_MAX_JERK = 600,
            LIFT_INTEGRATION_MAX_VELO = 0.6,
            LIFT_POS_TOLERANCE = 0.15843625,
            LIFT_INCHES_PER_TICK = 0.03168725,
            PRECISION_MODE_SCALE = 0.3,
            ANGLE_CLAW_CLOSED = 0,
            ANGLE_CLAW_OPEN = 62,
            ANGLE_ARM_DOWN = 100,
            ANGLE_PIVOT_FRONT = 17,
            ANGLE_PIVOT_BACK = 216,
            ANGLE_PASS_FRONT = 8,
            ANGLE_PASS_TILT = 45,
            ANGLE_PASS_BACK = 310,
            ANGLE_PASS_MINI_TILT = 17,
            TIME_CLAW = 0.0,
            TIME_LIFT_MEDIUM = 0.8,
            TIME_LIFT_TALL = 1,
            PASS_PIVOT_POINT = 0.4,
            PASS_MAX_VELO = 600,
            PASS_MAX_ACCEL = 1000,
            PASS_MAX_JERK = 3000;
}
