package org.firstinspires.ftc.teamcode.robot;

import com.acmerobotics.dashboard.config.Config;

@Config
public class RobotConfig {
    public static double
            HEIGHT_FLOOR = 0,
            HEIGHT_TWO = 1.25,
            HEIGHT_THREE = 2.5,
            HEIGHT_FOUR = 3.75,
            HEIGHT_FIVE = 5,
            HEIGHT_LOW = 6.2,
            HEIGHT_MEDIUM = 16.4,
            HEIGHT_TALL = 26.6,
            HEIGHT_STAGES_FOUR = 28.8,
            HEIGHT_STAGES_THREE = 19.2,
            HEIGHT_STAGES_TWO = 9.6,
            LIFT_kG_FOUR = 0.1,
            LIFT_kG_THREE = 0.08,
            LIFT_kG_TWO = 0.06,
            LIFT_kG_ONE = 0.04,
            LIFT_kP = 0.3,
            LIFT_kI = 0.1,
            LIFT_kD = 0.0,
            LIFT_UP_kV = 0.0285,
            LIFT_UP_kA = 0.004,
            LIFT_UP_kS = 0.001,
            LIFT_DOWN_kV = 0.015,
            LIFT_DOWN_kA = 0.0,
            LIFT_DOWN_kS = 0.001,
            LIFT_PID_FILTER_GAIN = 0.98,
            LIFT_VELO_FILTER_GAIN = 0.8,
            LIFT_ACCEL_FILTER_GAIN = 0.8,
            LIFT_JERK_FILTER_GAIN = 0.8,
            LIFT_MAX_VELO = 36,
            LIFT_MAX_ACCEL = 48,
            LIFT_MAX_JERK = 80,
            LIFT_INTEGRATION_MAX_VELO = 0.3,
            LIFT_POS_TOLERANCE = 0.0,
            LIFT_INCHES_PER_TICK = 0.03168725,
            PRECISION_MODE_SCALE = 0.3,
            ANGLE_CLAW_CLOSED = 5,
            ANGLE_CLAW_OPEN = 67,
            ANGLE_ARM_DOWN = 100,
            ANGLE_PIVOT_FRONT = 12,
            ANGLE_PIVOT_BACK = 210,
            ANGLE_PASS_FRONT = 8,
            ANGLE_PASS_TILT = 45,
            ANGLE_PASS_BACK = 310,
            ANGLE_PASS_MINI_TILT = 17,
            TIME_CLAW = 0.0,
            TIME_LIFT_MEDIUM = 0.8,
            TIME_LIFT_TALL = 1,
            CAMERA_FX = 578.272,
            CAMERA_FY = 578.272,
            CAMERA_CX = 402.145,
            CAMERA_CY = 221.506;
}
